# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd '$(build.sourcesDirectory)'      
      dir    
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(build.sourcesDirectory)'
    azureSubscription: 'Pay-As-You-Go(5bef145b-6b3c-4859-8322-66617be28aa8)'
    Destination: 'AzureBlob'    
    storage: 'danielportfoliosite'
    ContainerName: '$web'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(5bef145b-6b3c-4859-8322-66617be28aa8)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge -g Portfolio_DanielRobinson -n danielrportfolio --profile-name danielrobinsonportfolio-cdn --content-paths "/*"'
- task: PublishBuildArtifacts@1
